### ISSUE TITLE
Move to gitbook ?

### ISSUE THREAD

**Issue by morlay** [chantastic/reactpatterns#1]
Very cool summary about React.
There is a demo fork for publishing by [GitBook](https://www.gitbook.com):
https://morlay.github.com/react-patterns ([source code](https://github.com/morlay/react-patterns))

How do you think the proposal? 
And it will be helpful for i18n, too.

**Comment by chantastic** [comment]
thanks!

what are some of the headline benefits of creating a GitBook? i really like the sparse styling of what i have now but i'm open to it.

**Comment by morlay** [comment]
## Content only

Using gitbook, we could make most of commits about document content, which is clear for people who what to know the changes.

## Markdown compatibility with github

Comparing:
![image](https://cloud.githubusercontent.com/assets/1667873/17954152/83b23b22-6aab-11e6-8caf-743e3d9e3df4.png)
https://github.com/chantastic/reactpatterns.com/blob/gh-pages/_posts/2016-08-17-array-as-chidren.markdown
![image](https://cloud.githubusercontent.com/assets/1667873/17954158/8e19e95c-6aab-11e6-97ca-eb6abf142b92.png)
https://github.com/morlay/react-patterns/blob/master/en/react-patterns/array-as-chidren.md

Just want it is easier for contributor to updates.

## Plugins

Some plugin like https://github.com/azu/gitbook-plugin-include-codeblock
could help we split large source code to a single file.

## i18n

When the document is stable, we may translate it to other languages. 
GitBook is ready for that.

**Comment by chantastic** [comment]
Thanks for the additional clarification.

With the GitBook, is it possible to control styling? I'm not a big fan of the GitBook styling. It's in that strange middle ground where everything just looks sterile and unintentional.

**Comment by morlay** [comment]
Yes, we could rewrite the stylings, even the layouts.
Some project show how to do it:
- https://github.com/GitbookIO/theme-default
- https://github.com/GitbookIO/theme-api
- https://github.com/jadu/gitbook-theme

However, split the theme into another project may be better, 
and configure it in `book.json` as a `plugin`.

**Comment by chantastic** [comment]
Thank you again for the clarification. I think it's a good idea. I'm going to keep writing and see what happens with it. If there isn't a lot of interest in this, I don't want to spend the time to have moved it to a different platform. But I'll keep it in mind.

Thank you.

**Comment by DarrylD** [comment]
It's definitely a good idea as gitbook is popular with react libs. From a UX standpoint, everyone is comfortable with it's documenting style which could result in more people using and wanting to contribute.

I like the content as it stand now but, the format is **very** foreign and not friendly as a reference.

**Comment by damianesteban** [comment]
I think that it is a great idea.  It would be nice to keep a GitBook handy for reference.

Take a look - I started one here and just added one chapter: 

https://www.gitbook.com/book/damianesteban/react-patterns/details

Of course the explanations could be expanded upon.

**Comment by chantastic** [comment]
When you say "keep a GitBook handy" what does that look like? Could you
send me a link to where I oils read more about that feature/usage?

Thanks!

**Comment by morlay** [comment]
Ur, medium like comment, https://github.com/GitbookIO/plugin-comment

### usage

book.json

``` json
{
  "plugins": [
    "comment"
  ]
}
```

However, it works only when published on GitBook.com

**Comment by chantastic** [comment]
At the moment, I don't have intentions of making this a Gitbook.

I've restructured the project to be a `README` primarily, with a script that turns it into a styled HTML document (hosted on github pages).

I like the fact that it's consumable in both ways, depending on your preferred method of reading.

It might have a future as a Gitbook but not an immediate future.

Thank you so much for suggesting this and talking through the details with me.
