### ISSUE TITLE
Proxy component: can't pass 'ref'

### ISSUE THREAD

**Issue by ghengeveld** [chantastic/reactpatterns#13]
It should be noted that it's not allowed to pass `ref` down through a proxy component. You could circumvent this by using a custom 'xref' prop that is manually bound to the underlying component's `ref`.

I'm using the proxy component pattern extensively in [react-isomorphic-form](https://github.com/ghengeveld/react-isomorphic-form).

Related discussion: https://github.com/facebook/react/issues/4213

**Comment by chantastic** [comment]
this is noted in the second sentence. `They don’t hold state or refs; they’re just functions.`

how would you prefer it be noted?

**Comment by chantastic** [comment]
I'm going to leave this off for now.

The goal of this resource is "just the facts" and this concept is pretty advanced. Maybe a better fit for a more advanced target audience.

Thanks raising the issue!
