### ISSUE TITLE
States changes out of the component

### ISSUE THREAD

**Issue by Kikobeats** [chantastic/reactpatterns#23]
https://twitter.com/dan_abramov/status/824308413559668744

That's is a very nice pattern for make your state changes functions testeable.

Related: https://facebook.github.io/react/docs/react-component.html#setstate

**Comment by chantastic** [comment]
Thanks!

Yes, I've found using setState this way very useful in my apps.

I'll leave this open. I have a number of new patterns I'd like to write but haven't found time yet.

Thanks again!

**Comment by chantastic** [comment]
I actually have a tiny little lib that i use for toggle and increment (using the approach you linked): https://github.com/chantastic/restated/blob/master/index.js

**Comment by Kikobeats** [comment]
@chantastic good, I'm using toggle as well:

https://github.com/windtoday/windtoday-marketplace/blob/master/src/app/App/index.js#L44

Do you have plans for the repo? I can help you as norma contributor 💪

**Comment by nogtini** [comment]
Curious, decoupling the function from the class but still accessing `.step` and `.value` explicitly seems rigid.

**Comment by chantastic** [comment]
@yejodido it is. in our examples, we're both currying the key onto the setState callback.

```js
setState(toggle("arbitraryKey"))
```
