### ISSUE TITLE
I'm waiting for your new videos of React!

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [chantastic/reactpatterns#25]
# function component
https://codepen.io/chantastic/pen/EZwJMa

> this is very good demo, thanks a lot!

## React Component Type

1. class component
2. stateless component

> both of type components should be introduced as well!

**Comment by chantastic** [comment]
Thanks! Yeah, I'm running a bit behind on the video making.

Sadly, we had some family emergencies that took my focus off the vids. But hopefully new in classes in April.

I think the next set of videos [learnreact.com](http://learnreact.com) class will be on setState. Does that sound like a good next class?

**Comment by xgqfrms-GitHub** [comment]
Thanks for your reply!

**Comment by chantastic** [comment]
Also, there's a repo setup for the site. If you'd like, add an issue with classes you'd like to see. I'm always eager to hear what folks want to learn.

https://github.com/learnreact/learnreact.com

Thanks!
