### ISSUE TITLE
Proxy Component alternate names

### ISSUE THREAD

**Issue by bencoveney** [chantastic/reactpatterns#31]
Thanks for the great resource

> Proxy component
> (I’m not sure if this name makes sense)

Seems to me that the point of this component is to already have some standard things set.

Some alternative suggestions:
- **Boilerplate Component** Def: *sections of code that have to be included in many places with little or no alteration*
- **Preset Component** - Def: *set or adjust in advance of its use*
- **Preconfigured Component** - Def: *configured in advance*
- **Prepared Component** - Def: *created in advance; pre-planned*
- **Default[ed] Component** - Def: *revert[ed] automatically to a preselected option*
- **Prebuilt** - Def: *a structure that is constructed or assembled before [...] installation*
- **Prefab[ricated] Component** - Def: *to fabricate or construct beforehand*
- **Utility Component** or **Convention Component**

Can create a PR if any of these would fit in.

**Comment by chantastic** [comment]
Thanks for the issue.

Since writing this, I've seen a lot of people wrap these in with higher-order components, which makes sense. I think i might follow suit in the rewrite.
