### ISSUE TITLE
Make website mobile friendly

### ISSUE THREAD

**Issue by newyork-anthonyng** [chantastic/reactpatterns#35]
@chantastic Thank you for this!

I was reading this on my phone and noticed the webpage wasn't mobile friendly.

I'm guessing a `<meta name="viewport" content="width=device-width, initial-scale=1">` would fix this.

Let me know if you want me to create a Pull Request for this.

**Comment by chantastic** [comment]
I think this has been fixed thru one of the re-writes.

Thanks for reporting the issue!
