### ISSUE TITLE
Put live examples in CodeSandbox

### ISSUE THREAD

**Issue by newyork-anthonyng** [chantastic/reactpatterns#36]
@chantastic Do you think having examples on CodeSandbox would be helpful?

Letting beginners play around with the code samples would be valuable.

I can create a Pull Request for this is a good idea.

**Comment by TomYeoman** [comment]
+1 some live code examples really help.

**Comment by chantastic** [comment]
Thanks @newyork-anthonyng!

Obviously it's been a minute since you opened this issue.
It's a great idea and when I find cycles to re-write this resource it'll definitely be with some Code Sandboxes.
