### ISSUE TITLE
You open to design changes?

### ISSUE THREAD

**Issue by corysimmons** [chantastic/reactpatterns#38]
I could make this a bit easier to navigate, mobile-friendly, and migrate examples to CodeSandbox, if you'd be interested in that PR.

**Comment by tigranpetrossian** [comment]
Came here to suggest the same. Totally up for it. We could improve the readability quite a bit as well. Please respond when you've got a moment @chantastic

**Comment by chantastic** [comment]
hey folks. sorry for the delayed response. I suck at this part of the job.

I appreciate your offers to help. 

I'm planning a rewrite this year. I have some time slated between 3/26 and 4/6. Would gladly entertain ideas for improvement.

Right now, my plan is to add some sections and update the examples to use React Live—so visitors can make changes in place.

I'd also like to keep it primarily black and white. Thats pretty much all I got at this point

**Comment by corysimmons** [comment]
@chantastic What would you think about some little illustrations to go along with it? I'm bad at it but looking for a reason to practice.

**Comment by chantastic** [comment]
open to it. I had wanted to include in the first version but couldn't get the feel right. had wanted to really wanted to do a sumi ink style. but I too am not good at illustration.

**Comment by corysimmons** [comment]
If you do rewrite between 3/26-4/6, just leave some big areas open for diagrams and I'll try out that sumi ink style. :)

**Comment by chantastic** [comment]
Thanks for reaching out on this.
I'm going to close this just because we haven't moved forward on it.
I'll be re-writing this resource so maybe it's worth discussing while I'm making those changes.

Thanks again for the interest and support.
