### ISSUE TITLE
Layout components not always a cool stuff

### ISSUE THREAD

**Issue by Voronar** [chantastic/reactpatterns#41]
Layout components not always a cool stuff.
When you change layout all wrapped components will be re-rendered and it is additional complexity to handling this behavior.
A more appropriate approach is using maximum possibilities from `CSS` and `CSS Grid Layout` it is real salvation for this case.

**Comment by chantastic** [comment]
Thanks for the PR.
Sorry I'm bad at getting back to these.

CSS Grid Layout is great and Layout components can be used to provide a React API for grid areas.
