### ISSUE TITLE
UI/UX Changes

### ISSUE THREAD

**Issue by lsurasani** [chantastic/reactpatterns#43]
@chantastic hey! would you mind if I made a pull request with of a bunch of UI/UX changes? I'm thinking:

- New Font

- Consistent styling for each section

- Code snippets using PrismJS

- Mobile friendliness

Let me know what you think!

**Comment by chantastic** [comment]
thanks!

i'm actually in the process of restructuring the entire thing. very interested in feedback but would hate for you to invest any effort that would would eventually be replaced.

can you tell me more about what you have in mind?

**Comment by lsurasani** [comment]
hmm to break it down:
New font: self explanatory, but essentially changing it to something sans-serif and more "modern"-looking

Consistent Styling: I was thinking maybe at the top the Contents could be centered and then each bullet point could be a separate section (separated by a horizontal line possibly), with a title and any number of subheaders which are a different font size than the content. I also saw there was a lot of white space randomly between sections, so eliminating that as well might be good. Also maybe cleaning up the content would be a good idea (I've seen some headers that are capitalized, and some that aren't)

Mobile friendliness: I don't know off the top of my head how PrismJS (or other code snippet libraries) support mobile, but you could potentially just remove it entirely if they're on mobile (and just have the text) or reroute them to a new page since it's kind of hard to see on mobile anyway.

**Comment by chantastic** [comment]
Closing for now.
My good intentions haven't proven actionable yet.
Will dig this up again if i find time in 2020 to work on this.
